apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloapp.fullname" . }}
  labels:
    {{- include "helloapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{- if .Values.service.targetPort }} {{ .Values.service.targetPort }} {{- else }} http {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "helloapp.selectorLabels" . | nindent 4 }}
